// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzZLysDJgsVs3Z9GtT5CTcnQRRZ2grXrs',
    appId: '1:451325972278:web:91b56ad5bbe03ae6926d97',
    messagingSenderId: '451325972278',
    projectId: 'cham-cong-don-gian',
    authDomain: 'cham-cong-don-gian.firebaseapp.com',
    storageBucket: 'cham-cong-don-gian.firebasestorage.app',
    measurementId: 'G-NJ9KNH0046',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_F4ILRTunE4DlvkN5WiMW3hmPOplxHEU',
    appId: '1:451325972278:android:572634e46593f128926d97',
    messagingSenderId: '451325972278',
    projectId: 'cham-cong-don-gian',
    storageBucket: 'cham-cong-don-gian.firebasestorage.app',
  );
}
